version: '3.8'

services:
  gql:
    container_name: botedb-gql
    build:
      context: .
      target: build
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - botedb-gql-node_modules:/app/node_modules
    command: sh -c 'yarn start:dev'

volumes:
  botedb-gql-node_modules:
